---
- name: Criar diretório /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Baixar chave GPG oficial do Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Adicionar repositório oficial do Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker

- name: Instalar Docker CE e Docker Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Iniciar e habilitar o serviço do Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Adicionar usuário ao grupo docker
  ansible.builtin.user:
    name: "{{ stoat_user }}"
    groups: docker
    append: yes

- name: Resetar conexao SSH para carregar novo grupo docker
  ansible.builtin.meta: reset_connection
